name: Build Image
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'cloudflare-warp version(without "v" prefix) to build from'
        required: true
      gost_version:
        description: 'Gost binary version(without "v" prefix) to build from'
        required: true
jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          build-args: |
            WARP_VERSION=${{ github.event.inputs.version }}
            GOST_VERSION=${{ github.event.inputs.gost_version }}
          push: true
          tags: seancheung/warp:${{ github.event.inputs.version }},seancheung/warp:latest